### PR TITLE
Demo page

### PR DESCRIPTION
**Pull request by robertdown**
Things may be a bit weird here, because of the way the new repo interacted with the old one I had to basically force a merge between master and the demo-page...

### CODE REVIEW

**Comment by bradymiller** [comment]
Do you want me to get this into 1 commit?
(easy for me to do)

**Comment by bradymiller** [comment]
Actually, there are a huge amount of conflicts to deal with since code changes have made to master. Gonna likely make sense to duplicate your work on master.
Also, having the public directory is nice to ensure changes don't do crazy things. Is there a specific reason why we can't keep this?

**Comment by robertdown** [comment]
It's generally bad practice to keep the contents of a static folder inside a vcs. I'll clean up the conflicts. Running `hugo` will generate the site for you prior to production release

**Comment by bradymiller** [comment]
I know its bad practice, but it gives me a sanity check before I bring something to the site live :)
(ie. it's a bit vital in my work flow)

**Comment by robertdown** [comment]
Closed because of all the commits - will submit a fresh PR

**Pull request closed without merging**
