### PR TITLE
Download page

### PR DESCRIPTION
**Pull request by robertdown**

### CODE REVIEW

**Comment by robertdown** [comment]
capture

**Comment by MatthewVita** [comment]
Oh Woah!!!!!!!!!

Only nitpick is to fix Tux's foot (he only has one foot)

**Comment by bradymiller** [comment]
Wow! very nice
Noted some issues listed below:
-release date should be 2017-02-15
-docker has no install or upgrade guide. download page currently has a link to a forum thread with howtos and tips.
-windows package display name isn't right
-windows xampp does not have an upgrade guide
-windows xampp package display name isn't wright
-linux mint should be the same links as debian/ubuntu sections (rather than the windows zip package)
-appliance does not have an upgrade guide
-Missing AWS cloud section
-Missing link to show users where to find the prior version packages
-Daily snapshots section is not utilizing the daily builds (the github zipped packages don't work with the current documentation).
-Development tip docker is not listed

**Comment by robertdown** [comment]
WTF.... where'd his other foot go! Will tidy everything up

**Comment by robertdown** [comment]
- [x] ~release date should be 2017-02-15~
- [x] docker has no install or upgrade guide. download page currently has a link to a forum thread with howtos and tips.
- [x] windows package display name isn't right
- [x] windows xampp does not have an upgrade guide
- [x] windows xampp package display name isn't right
- [ ] linux mint should be the same links as debian/ubuntu sections (rather than the windows zip package)
- [x] appliance does not have an upgrade guide
- [ ] Missing AWS cloud section
- [x] Missing link to show users where to find the prior version packages
- [ ] Daily snapshots section is not utilizing the daily builds (the github zipped packages don't work with the current documentation).
- [ ] Development tip docker is not listed

**Pull request closed without merging**
