### PR TITLE
Adding donate button to hero, improving font support

### PR DESCRIPTION
**Pull request by robertdown**

### CODE REVIEW

**Comment by bradymiller** [comment]
When I run hugo, I get the following error:
```
Building sites … ERROR 2018/09/24 00:30:01 Failed to parse date '2018-22-06T20:57:39-05:00' in page demo/_index.md
```

**Comment by bradymiller** [comment]
The new Donate button goes to the Support wiki page

**Comment by bradymiller** [comment]
Looks like the facebook and twitter links at top of page disappeared

**Comment by bradymiller** [comment]
Would it make sense to direct both the donate buttons to the donate web page you made (rather than directly link to paypal). If so, probably a good idea to do this within the donate link that is on the About page in OpenEMR.

**Comment by robertdown** [comment]
**The new Donate button goes to the Support wiki page**
Oops, Fixed

**Looks like the facebook and twitter links at top of page disappeared**
Yep, the main menu is getting crowded, I pulled them intentionally

**Would it make sense to direct both the donate buttons to the donate web page you made**
Yes, I think that makes sense

New commits added to address above issues

**Pull request merged**
